// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbnpcqbltnthjdofrruw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZibnBjcWJsdG50aGpkb2ZycnV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODU5MzUsImV4cCI6MjA2MDA2MTkzNX0.FDmDB21WUvWB7YvpOkCS9zAy6dmOU97v-J85qo8gIzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);